[build]
  command = "npm install && npm run build:production"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  VITE_ENABLE_DEMO_MODE = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
