# Netlify Configuration for Surveasy
[build]
  # Build command for Vite React app
  command = "npm run build"
  
  # Directory containing the built app
  publish = "dist"
  
  # Node.js version
  environment = { NODE_VERSION = "18" }

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables for production
[build.environment]
  # Whisper service URL (will be demo mode on Netlify)
  VITE_WHISPER_SERVICE_URL = ""
  VITE_APP_NAME = "Surveasy"
  VITE_APP_VERSION = "1.0.0"
  VITE_DEBUG_MODE = "false"
  VITE_ENABLE_LOGGING = "false"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache fonts
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Netlify Functions (optional - for basic API endpoints)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
